[service.worker]
balance-strategy = "round-robin"

[service.worker.worker-config]
timeout = true
max-duration = 60000
# Retry config
max-retries = 25
delay = 1000
delay-offset = 10000
max-delay = 86400000 # 24 hours
backoff-strategy = "exponential"

[service.worker.worker-config.pg]
success-action = "delete"
failure-action = "archive"

[service.worker.pg.queue-fetch-config]
error-delay = 10000
empty-delay = 10000

[service.worker.pg.periodic]
enable = true
stale-cleanup = "auto-clean-stale"

[service.worker.sidekiq.periodic]
stale-cleanup = "auto-clean-stale"

