# Rules to use in addition to the defaults: https://github.com/get-woke/woke/blob/main/pkg/rule/default.yaml
rules:
  # The default rules don't have `master`, only `master-slave`
  - name: master
    terms:
      - master
    alternatives:
      - main
      - primary
      - leader
