[package]
name = "roadster"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Config
config = "0.14.0"
dotenvy = "0.15.7"

# Tracing
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
opentelemetry-semantic-conventions = "0.14.0"

# Controllers
axum = "0.7.4"
aide = { version = "0.13.2", features = ["axum", "redoc", "scalar", "macros"] }
schemars = "0.8.16"
tower-http = { version = "0.5.1", features = ["trace", "timeout", "request-id", "util", "normalize-path", "sensitive-headers"] }
tower = "0.4.13"

# DB
sea-orm = { version = "0.12.15", features = ["debug-print", "runtime-tokio-rustls", "sqlx-postgres", "macros"] }

# Others
anyhow = "1.0.81"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_with = { version = "3.7.0", features = ["macros"] }
strum = "0.26.1"
strum_macros = "0.26.1"
async-trait = "0.1.77"
# Todo: minimize tokio features included in `roadster`
tokio = { version = "1.35.1", features = ["full", "macros"] }
itertools = "0.12.1"
serde_json = "1.0.114"
toml = "0.8.12"
lazy_static = "1.4.0"
url = { version = "2.5.0", features = ["serde"] }

[dev-dependencies]
cargo-husky = { version = "1.5.0", features = ["default", "run-cargo-check", "run-cargo-clippy", "run-cargo-fmt", "run-cargo-test"] }
