[package]
name = "roadster"
version = "0.1.1"
edition = "2021"
publish = true
description = "A \"Batteries Included\" web framework for rust designed to get you moving fast."
repository = "https://github.com/roadster-rs/roadster"
license = "MIT OR Apache-2.0"
keywords = ["web", "framework"]
categories = ["web-programming", "web-programming::http-server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sidekiq", "db-sql", "open-api", "jwt-ietf", "cli", "otel"]
sidekiq = ["dep:rusty-sidekiq", "dep:bb8", "dep:num_cpus"]
db-sql = ["dep:sea-orm", "dep:sea-orm-migration"]
open-api = ["dep:aide", "dep:schemars"]
jwt = ["dep:jsonwebtoken"]
jwt-ietf = ["jwt"]
jwt-openid = ["jwt"]
cli = ["dep:clap"]
otel = ["dep:opentelemetry", "dep:opentelemetry_sdk", "dep:opentelemetry-otlp", "dep:tracing-opentelemetry"]

[dependencies]
# Config
config = "0.14.0"
dotenvy = "0.15.7"

# Tracing
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
opentelemetry-semantic-conventions = "0.14.0"
opentelemetry = { version = "0.22.0", features = ["trace", "metrics", "logs"], optional = true }
opentelemetry_sdk = { version = "0.22.1", features = ["tokio", "rt-tokio", "metrics", "logs", "trace"], optional = true }
opentelemetry-otlp = { version = "0.15.0", features = ["metrics", "trace", "logs"], optional = true }
tracing-opentelemetry = { version = "0.23.0", features = ["metrics"], optional = true }

# Controllers
axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["trace", "timeout", "request-id", "util", "normalize-path", "sensitive-headers", "catch-panic", "compression-full", "decompression-full", "limit"] }
aide = { version = "0.13.4", features = ["axum", "redoc", "scalar", "macros"], optional = true }
schemars = { version = "0.8.17", optional = true }

# DB
sea-orm = { version = "1.0.0-rc.4", features = ["debug-print", "runtime-tokio-rustls", "sqlx-postgres", "macros"], optional = true }
sea-orm-migration = { version = "1.0.0-rc.4", features = ["runtime-tokio-rustls", "sqlx-postgres"], optional = true }

# Workers
# Todo: the default `rss-stats` feature has a dependency that currently can't be satisfied (memchr: ~2.3)
rusty-sidekiq = { version = "0.10.5", default-features = false, optional = true }
bb8 = { version = "0.8.3", optional = true }
num_cpus = { version = "1.16.0", optional = true }

# Rust async
# Todo: minimize tokio features included in `roadster`
tokio = { version = "1.37.0", features = ["full", "macros"] }
# For CancellationToken
tokio-util = { version = "0.7.11" }
async-trait = "0.1.80"

# Auth
jsonwebtoken = { version = "9.3.0", optional = true }

# CLI
clap = { version = "4.5.4", features = ["derive", "string"], optional = true }

# Others
anyhow = "1.0.82"
serde = "1.0.200"
serde_derive = "1.0.200"
serde_with = { version = "3.8.1", features = ["macros", "chrono_0_4"] }
strum = "0.26.2"
strum_macros = "0.26.2"
itertools = "0.12.1"
serde_json = "1.0.116"
toml = "0.8.12"
url = { version = "2.5.0", features = ["serde"] }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
futures-core = "0.3.30"
chrono = { version = "0.4.38", features = ["serde"] }
byte-unit = { version = "5.1.4", features = ["serde"] }
convert_case = "0.6.0"
const_format = "0.2.32"
typed-builder = "0.18.2"
num-traits = "0.2.19"
log = "0.4.21"

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = ["user-hooks"] }

[workspace]
members = [".", "examples/*"]

[package.metadata.docs.rs]
# Have docs.rs pass `--all-features` to ensure all features have their documentation built.
all-features = true
