# The config file can be validated using https://api.codecov.io/validate
# `curl -X POST --data-binary @codecov.yml https://codecov.io/validate`
#
# https://docs.codecov.com/docs/common-recipe-list

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
github_checks:
  # Install the codecov browser extension to see coverage annotations in GitHub.
  # https://docs.codecov.com/docs/the-codecov-browser-extension
  annotations: false
comment:
  # https://docs.codecov.com/docs/pull-request-comments#layout
  layout: "header, files, footer"
  hide_project_coverage: false
  require_changes: true
