# Converted from this git-cliff example: https://github.com/orhun/git-cliff/blob/main/examples/github-keepachangelog.toml

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""

# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

### Details\

{% for group, commits in commits | group_by(attribute="group") %}
    #### {{ group | upper_first }}
    {%- for commit in commits %}
        - {{ commit.message | upper_first | trim }}\
            {% if commit.github.username %} by @{{ commit.github.username }}{%- endif -%}
            {% if commit.github.pr_number %} in \
              [#{{ commit.github.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.github.pr_number }}) \
            {%- endif -%}
    {% endfor %}
{% endfor %}

{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ## New Contributors
{%- endif -%}

{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor %}\n
"""

trim = true
protect_breaking_commits = true
sort_commits = "newest"

# https://release-plz.ieni.dev/docs/config#the-commit_preprocessors-field
[[changelog.commit_preprocessors]]
pattern = "  +"
replace = " "

[[changelog.commit_preprocessors]]
pattern = "\\(#([0-9]+)\\)"
replace = "([#${1}](https://github.com/roadster-rs/roadster/issues/${1}))"

[[changelog.commit_preprocessors]]
pattern = "https://github.com/[^ ]/issues/([0-9]+)"
replace = "[Issue #${1}]"

[[changelog.commit_preprocessors]]
pattern = 'Merged PR #[0-9]: (.*)'
replace = "$1"

[[changelog.commit_preprocessors]]
pattern = ' *(:\w+:|[\p{Emoji_Presentation}\p{Extended_Pictographic}\u{200D}]) *'
replace = ""

[[changelog.commit_preprocessors]]
pattern = "Merge pull request #([0-9]+) from [^ ]+"
replace = "PR # [${1}](https://github.com/roadster-rs/roadster/pull/${1}):"

[[changelog.commit_preprocessors]]
pattern = "https://github.com/orhun/git-cliff/commit/([a-f0-9]{7})[a-f0-9]*"
replace = "commit # [${1}](${0})"

[[changelog.commit_preprocessors]]
pattern = "([ \\n])(([a-f0-9]{7})[a-f0-9]*)"
replace = "${1}commit # [${3}](https://github.com/roadster-rs/roadster/commit/${2})"


[[changelog.commit_parsers]]
message = "^.*: add"
group = "Added"

[[changelog.commit_parsers]]
message = "^.*: support"
group = "Added"

[[changelog.commit_parsers]]
message = "^.*: remove"
group = "Removed"

[[changelog.commit_parsers]]
message = "^.*: delete"
group = "Removed"

[[changelog.commit_parsers]]
message = "^test"
group = "Fixed"

[[changelog.commit_parsers]]
message = "^fix"
group = "Fixed"

[[changelog.commit_parsers]]
message = "^.*: fix"
group = "Fixed"

[[changelog.commit_parsers]]
message = "^.*"
group = "Changed"


# https://release-plz.ieni.dev/docs/config#the-link_parsers-field
[[changelog.link_parsers]]
pattern = "#(\\d+)"
href = "https://github.com/roadster-rs/roadster/issues/$1"

[[changelog.link_parsers]]
pattern = "RFC(\\d+)"
text = "ietf-rfc$1"
href = "https://datatracker.ietf.org/doc/html/rfc$1"
