[app]
name = "Minimal Example"

[service.http]
enable = true
host = "127.0.0.1"
port = 3000

[tracing]
level = "debug"

[database]
auto-migrate = true
connect-timeout = 5000
acquire-timeout = 5000
idle-timeout = 60
min-connections = 0
max-connections = 10

[worker.sidekiq]
queues = ["default"]
