[tracing]
format = "pretty"

[auth.jwt]
secret = "secret-dev"

[database]
# For the purposes of this example, the db uri is set in
# app-builder/src/config/example_async_source.rs
#uri = "postgres://roadster:roadster@localhost:5432/example_dev"

[service.sidekiq]
num-workers = 2

[service.sidekiq.redis]
# For the purposes of this example, the redis uri is set in
# app-builder/src/config/example_async_source.rs
#uri = "redis://localhost:6379"
