[tracing]
format = "pretty"

metrics-export-interval = 1000

[tracing.otlp.endpoint]
protocol = "grpc"
url = "http://localhost:4317"

[auth.jwt]
secret = "secret-dev"

[database]
# For the purposes of this example, the db uri is set in
# app-builder/src/config/example_async_source.rs
#uri = "postgres://roadster:roadster@localhost:5432/example_dev"

[service.worker.sidekiq]
num-workers = 2

[service.worker.sidekiq.redis]
# For the purposes of this example, the redis uri is set in
# app-builder/src/config/example_async_source.rs
#uri = "redis://localhost:6379"
