[service.http.middleware.sensitive-request-headers]
enable = false

[service.http.middleware.sensitive-response-headers]
enable = false

[service.http.middleware.tracing]
request-headers-allow-all = true
response-headers-allow-all = true
query-params-allow-all = true
