[app]
name = "Full Example"

[service.http]
# Listen on any ipv4 or ipv6 addr, useful to allow connections from LAN for local dev
# host = "[::]"
# Listen only on localhost
host = "127.0.0.1"
port = 3000

[service.grpc]
host = "127.0.0.1"
port = 3001
