[tracing]
format = "pretty"

[auth.jwt]
secret = "secret-test"

[database]
uri = "postgres://roadster:roadster@localhost:5433/full_test"

[service.sidekiq]
num-workers = 2

[service.sidekiq.redis]
uri = "redis://localhost:6380"