[tracing]
format = "compact"
trace-propagation = true

# Hide some noisy logs from traces
trace-filters = [
    "h2=warn",
    "tower::buffer::worker=warn",
    "opentelemetry_sdk=warn",
    "opentelemetry-otlp=warn",
    "hyper_util::client::legacy::connect::http=warn",
]
