#!/usr/bin/env bash

# Exit immediately if any command returns non-zero exit status.
set -e

# `fmt` doesn't depend on which features are enabled
echo "### fmt --all --check ###"
cargo fmt --all --check

# With no features
echo "### build --no-default-features ###"
RUSTFLAGS="-D warnings" cargo build --no-default-features
echo "### nextest run --no-default-features ###"
cargo nextest run --no-default-features --no-fail-fast
# Nextest doesn't support doc tests, run those separately
echo "### test --doc --no-default-features ###"
cargo test --doc --no-default-features --no-fail-fast
echo "### check --no-default-features ###"
cargo check --no-default-features
echo "### clippy --all-targets --no-default-features -- -D warnings ###"
cargo clippy --all-targets --no-default-features -- -D warnings

# With default features
echo "### build ###"
cargo build
echo "### nextest run ###"
cargo nextest run --no-fail-fast
# Nextest doesn't support doc tests, run those separately
echo "### test --doc ###"
cargo test --doc --no-fail-fast
echo "### check ###"
cargo check
echo "### clippy --all-targets -- -D warnings ###"
cargo clippy --all-targets -- -D warnings

# With all features
echo "### build --all-features ###"
cargo build --all-features
echo "### nextest run --all-features --workspace ###"
cargo nextest run --all-features --no-fail-fast --workspace
# Nextest doesn't support doc tests, run those separately
echo "### test --doc --all-features --workspace ###"
cargo test --doc --all-features --no-fail-fast --workspace
echo "### check --all-features --workspace ###"
cargo check --all-features --workspace
echo "### clippy --workspace --all-targets --all-features -- -D warnings ###"
cargo clippy --workspace --all-targets --all-features -- -D warnings

echo "### cargo doc --all-features --no-deps ###"
RUSTDOCFLAGS="-D rustdoc::all -A rustdoc::private_intra_doc_links" cargo doc --all-features --no-deps

echo "### cargo minimal-versions check --direct --all-features ###"
cargo minimal-versions check --direct --all-features --no-dev-deps
