#!/usr/bin/env bash

# Checks that don't depend on which features are enabled
echo "### fmt --all -- --check ###"
cargo fmt --all -- --check
echo "### clippy --workspace -- -D warnings ###"
cargo clippy --workspace -- -D warnings

# Without default features
echo "### test --no-default-features --workspace ###"
cargo test --no-default-features --workspace
echo "### check --no-default-features --workspace ###"
cargo check --no-default-features --workspace

# With default features
echo "### test --workspace ###"
cargo test --workspace
echo "### check --workspace ###"
cargo check --workspace

# With all features
echo "### test --all-features --workspace ###"
cargo test --all-features --workspace
echo "### check --all-features --workspace ###"
cargo check --all-features --workspace
