[package]
name = "database-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
roadster = { path = "../../.." }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
clap = { workspace = true }
