[tracing]
trace-propagation = true

metrics-export-interval = 1000

# Set the endpoint to use for traces
[tracing.otlp.trace-endpoint]
# Traces can be exported via grpc when the `otel-grpc` feature is enabled
protocol = "grpc"
url = "http://localhost:4317"
# Traces can also be exported via http`.
# The `http` protocol is enabled by default when the `otel` feature is enabled.
#protocol = "http"
#url = "http://localhost:4318/v1/traces"

[tracing.otlp.metric-endpoint]
# Traces can be exported via grpc when the `otel-grpc` feature is enabled
protocol = "grpc"
url = "http://localhost:4317"
# Traces can also be exported via http`.
# The `http` protocol is enabled by default when the `otel` feature is enabled.
#protocol = "http"
#url = "http://localhost:4318/v1/metrics"
