[service.sidekiq]
balance-strategy = "round-robin"

[service.sidekiq.periodic]
stale-cleanup = "auto-clean-stale"

[service.sidekiq.app-worker]
max-retries = 25
timeout = true
max-duration = 60
disable-argument-coercion = false
