[tracing]
format = "pretty"

[auth.jwt]
secret = "secret-test"

[database]
uri = "postgres://roadster:roadster@localhost:5432/example_dev"
temporary-test-db = true

[service.sidekiq]
num-workers = 2

[service.sidekiq.redis]
uri = "redis://localhost:6379"
