# Test that test groups are assigned correctly using:
# `cargo nextest show-config test-groups`
[test-groups]
# Mocks of static methods need to run sequentially.
cli-static-mock = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(#api::cli::tests::*)'
test-group = "cli-static-mock"
