[tracing]
format = "pretty"

[auth.jwt]
secret = "secret-dev"

[database]
uri = "postgres://roadster:roadster@localhost:5432/example_dev"
#uri = "postgres://postgres:postgres@localhost:5433/postgres"
