//! [`model`] contains our application-specific logic for interacting with the DB. It is kept
//! separate from the [`entity`] module because SeaORM will override all code in the [`entity`]
//! module when we generate code from our DB schema.

/// [`entity`] contains the raw code generated by SeaORM to represent our DB schema. It needs to
/// be in the same crate as our application-specific logic in order to use `impl` on the models
/// contained in [`entity`].
pub mod entity;

pub mod user;
