# Originally copied from https://github.com/leptos-rs/book/blob/f6683d42f2a9f67230cfdf9fb94e094f1c8bfca4/.github/workflows/publish_mdbook.yml#L1

name: Book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MDBOOK_VERSION: 0.4.40

jobs:
  test-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: rui314/setup-mold@e16410e7f8d9e167b74ad5697a9089a35126eb50
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
      - uses: taiki-e/install-action@86c23eed46c17b80677df6d8151545ce3e236c61
        with:
          tool: mdbook

      - uses: taiki-e/install-action@86c23eed46c17b80677df6d8151545ce3e236c61
        with:
          tool: just

      # protoc is needed to build examples that have grpc enabled
      - uses: taiki-e/install-action@86c23eed46c17b80677df6d8151545ce3e236c61
        with:
          tool: protoc


      - name: Test mdbook
        run: just test-book

      - name: Test mdbook examples
        run: just test-book-examples
