# Originally copied from https://github.com/leptos-rs/book/blob/f6683d42f2a9f67230cfdf9fb94e094f1c8bfca4/.github/workflows/publish_mdbook.yml#L1

name: Book

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MDBOOK_VERSION: 0.4.40

jobs:
  test-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@mdbook
      - uses: taiki-e/install-action@just
      - name: Update rust
        run: |
          cargo --version
          rustup update

      - name: Test mdbook
        run: just test-book

      - name: Test mdbook examples
        run: just test-book-examples
