name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  roadster_feature_powerset:
    name: Feature powerset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-hack
      - name: Test
        run: cargo hack test --no-fail-fast --feature-powerset --workspace
      - name: Check
        run: cargo hack check --feature-powerset --no-dev-deps --workspace
      - name: Clippy
        run: cargo hack clippy --workspace --all-targets --feature-powerset -- -D warnings

  check_formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Formatting
        run: cargo fmt --all --check

  check-docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docs
        env:
          RUSTDOCFLAGS: "-D rustdoc::all"
        run: cargo doc --all-features --no-deps
