name: Cargo Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  roadster_no_features:
    name: Roadster no features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --no-default-features --no-fail-fast
      - name: Check
        run: cargo check --no-default-features
      - name: Clippy
        run: cargo clippy --no-default-features -- -D warnings
      - name: Formatting
        run: cargo fmt --no-default-features -- --check
