name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # `cargo hack --each-feature` runs the given command for each feature, including "no features", "all features",
  # and the `default` feature.
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@nextest
      # protoc is needed to build examples that have grpc enabled
      - uses: taiki-e/install-action@protoc
      - name: Build
        run: cargo hack build --each-feature --workspace --clean-per-run --log-group github-actions

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@nextest
      # protoc is needed to build examples that have grpc enabled
      - uses: taiki-e/install-action@protoc
      - name: Test
        run: cargo hack nextest run --no-fail-fast --each-feature --clean-per-run --log-group github-actions

  doc_test:
    name: Doc tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      # protoc is needed to build examples that have grpc enabled
      - uses: taiki-e/install-action@protoc
      - name: Doc test
        run: cargo hack test --doc --no-fail-fast --each-feature --log-group github-actions

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      # protoc is needed to build examples that have grpc enabled
      - uses: taiki-e/install-action@protoc
      - name: Check
        run: cargo hack check --each-feature --no-dev-deps --log-group github-actions

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      # protoc is needed to build examples that have grpc enabled
      - uses: taiki-e/install-action@protoc
      - name: Clippy
        run: cargo hack clippy --all-targets --each-feature --log-group github-actions -- -D warnings

  deny:
    name: Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
          arguments: --all-features
          command-arguments: "-A duplicate advisories ban sources"

  # https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version
  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack check --rust-version --all-targets --ignore-private --log-group github-actions

  # https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version
  minimal_direct_deps:
    name: Direct dep min version check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@cargo-minimal-versions
      - run: cargo minimal-versions check --direct --all-features

  check_formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Formatting
        run: cargo fmt --all --check

  check_docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Docs
        env:
          RUSTDOCFLAGS: "-D rustdoc::all -A rustdoc::private_intra_doc_links"
        run: cargo doc --all-features
