name: Cargo Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  roadster_no_features:
    name: Roadster no features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --no-fail-fast --no-default-features
      - name: Check
        run: cargo check --no-default-features
      - name: Clippy
        run: cargo clippy --no-default-features -- -D warnings

  roadster_default_features:
    name: Roadster default features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --no-fail-fast
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy -- -D warnings

  roadster_with_all_feature_combinations:
    name: Roadster with all feature combinations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - sidekiq
          - db-sql
          - open-api
          - sidekiq,db-sql
          - sidekiq,open-api
          - db-sql,open-api
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --no-fail-fast --no-default-features --features ${{matrix.features}}
      - name: Check
        run: cargo check --no-default-features --features ${{matrix.features}}
      - name: Clippy
        run: cargo clippy --no-default-features --features ${{matrix.features}} -- -D warnings

  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Formatting
        run: cargo fmt -- --check
