name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  roadster_no_features:
    name: No features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --no-fail-fast --no-default-features --workspace
      - name: Check
        run: cargo check --no-default-features --workspace

  roadster_default_features:
    name: Default features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --no-fail-fast --workspace
      - name: Check
        run: cargo check --workspace

  roadster_all_features:
    name: All features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --no-fail-fast --all-features --workspace
      - name: Check
        run: cargo check --all-features --workspace

  roadster_with_all_feature_combinations:
    name: Feature combos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Todo: Is there a way to generate this list automatically?
        features:
          - sidekiq
          - db-sql
          - open-api
          - sidekiq,db-sql
          - sidekiq,open-api
          - db-sql,open-api
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test --no-fail-fast --no-default-features --features ${{matrix.features}} --workspace
      - name: Check
        run: cargo check --no-default-features --features ${{matrix.features}} --workspace

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy --workspace -- -D warnings

  check_formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Formatting
        run: cargo fmt --all -- --check
