name: Test coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Collect test coverage
    runs-on: ubuntu-latest
    env:
      # The `coverage_nightly` cfg value is not recognized, so we need to allow unknown
      # cfg values in order to have the build succeed.
      RUSTFLAGS: -D warnings -A unexpected_cfgs
      CARGO_TERM_COLOR: always
    steps:
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1
        with:
          toolchain: nightly
          components: llvm-tools-preview
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: rui314/setup-mold@e16410e7f8d9e167b74ad5697a9089a35126eb50
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0
      - name: Install zsh
        run: sudo apt install -y zsh
      - uses: taiki-e/install-action@735e5933943122c5ac182670a935f54a949265c1
        with:
          tool: just,nextest,cargo-llvm-cov
      - name: Collect coverage data
        # Generate coverage report using nextest.
        run: |
          just coverage-tests
          cargo llvm-cov report --doctests --lcov --output-path lcov.info
      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: lcov.info
