name: Test coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Collect test coverage
    runs-on: ubuntu-latest
    env:
      # The `coverage_nightly` cfg value is not recognized, so we need to allow unknown
      # cfg values in order to have the build succeed.
      RUSTFLAGS: -D warnings -A unexpected_cfgs
      CARGO_TERM_COLOR: always
    steps:
      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          toolchain: nightly
          components: llvm-tools-preview
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: rui314/setup-mold@e16410e7f8d9e167b74ad5697a9089a35126eb50
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
      - name: Install zsh
        run: sudo apt install -y zsh
      - uses: taiki-e/install-action@735e5933943122c5ac182670a935f54a949265c1
        with:
          tool: just,nextest,cargo-llvm-cov
      - name: Collect coverage data
        # Generate coverage report using nextest.
        run: |
          just coverage-tests
          cargo llvm-cov report --doctests --lcov --output-path lcov.info
      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: lcov.info
