name: DEI Checks

on:
  push:
    branches: [ main, v0.8 ]
  pull_request:
    branches: [ main, v0.8 ]
  workflow_dispatch:

jobs:
  inclusive_language:
    name: Check for inclusive language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: get-woke/woke-action@b2ec032c4a2c912142b38a6a453ad62017813ed0
        with:
          fail-on-error: true
          woke-args: -c .config/woke.yml
