name: DEI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  inclusive_language:
    name: Check for inclusive language
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: get-woke/woke-action@b2ec032c4a2c912142b38a6a453ad62017813ed0
        with:
          fail-on-error: true
          woke-args: -c .config/woke.yml
