# https://release-plz.ieni.dev/docs/github/quickstart#example-release-pr-and-release

name: Release PR

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    # Release PRs are created after the `Feature Powerset` workflow completes successfully. Currently,
    # `Feature Powerset` runs once a week, so release PRs will also be created once a week.
    workflows: [ Feature Powerset ]
    types:
      - completed

jobs:
  release-pr:
    name: Release PR
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1
        with:
          toolchain: stable
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@57d6b19001af9a5f21e461fc67adbb5a5f4d5ebe
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  on-powerset-failure:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure') }}
    steps:
      - run: echo 'The `Feature Powerset` workflow failed, skipping release.'
