# A separate workflow to check semver compatibility. This is in a separate workflow
# to avoid semver check failures (which will always happen when we're intentionally working on a
# new set of breaking changes) from making it look like our CI checks are failing.

name: Semver

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_semver:
    name: Check Semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Update rust
        run: |
          cargo --version
          rustup update
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
